version: "3.3"

services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://message_db_image/message -schemas=public -user=dev -password=dev -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/sql:/flyway/sql
    depends_on:
      - message_db_image
  message_db_image:
    build: src/main/docker/database
    image: message_db_image
    expose:
      - "5432"
    ports:
      - "6011:5432"
    container_name: message-database
    environment:
      - POSTGRES_USERNAME=dev
      - POSTGRES_PASSWORD=dev
  message_service_image:
    build: .
    image: message_service_image
    volumes:
      - ./target:/opt/message-service
    ports:
      - "8090:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_SERVER=message-database
      - DB_PORT=5433
      - DB_USERNAME=DEV
      - DB_PASSWORD=DEV
    links:
      - message_db_image
    container_name: message-service
