version: "3.3"

services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://example_db_image/example -schemas=public -user=dev -password=dev -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/sql:/flyway/sql
    depends_on:
      - example_db_image
  example_db_image:
    build: src/main/docker/database
    image: example_db_image
    expose:
      - "5432"
    ports:
      - "6011:5432"
    container_name: example-database
    environment:
      - POSTGRES_USERNAME=dev
      - POSTGRES_PASSWORD=dev
  example_service_image:
    build: .
    image: example_service_image
    volumes:
      - ./target:/opt/example-service
    ports:
      - "8090:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_SERVER=example-database
      - DB_PORT=5433
      - DB_USERNAME=DEV
      - DB_PASSWORD=DEV
    links:
      - example_db_image
    container_name: example-service
